### ISSUE TITLE
Snyk plugin for Rider fails to scan projects in solution with "Could not detect supported target files" error

### ISSUE THREAD

**Issue by dlaudams** [snyk/snyk-intellij-plugin#175]
The Snyk Vulnerability Scanner v2.3.0 plugin for Rider on MacOS is failing to scan with the error "Could not detect supported target files in {project path}" error.

It seems the scanner is not detecting projects that belong to the solution.

When I open the child project directly in Rider then Snyk is able to scan the project as expected.

**Comment by ArtsiomCh** [comment]
Hi Daniel
Do you try to perform Open Source Security or Code Security/Quality (or both) type of scan?
If first one, did you try to add `--all-projects` to Snyk project settings?
![image](https://user-images.githubusercontent.com/14268320/134357806-5df56219-3e07-434d-adb9-6f25097ad124.png)

**Comment by dlaudams** [comment]
Hi @ArtsiomCh,

Yes it was the Open Source Security scan that failed.

Thanks, yes adding the `--all-projects` parameter to the Synk settings fixes the issue for that solution.

It seems this setting does not apply to any other solution I open. i.e., this needs configuring manually for every solution to avoid this error.

In my opinion I think scanning all projects should be the default when opening any `*.sln`.

Thanks,
Daniel.

**Comment by ArtsiomCh** [comment]
Glad to know it helps! And yes, you need to manually do it for each new solution opened, as that setting is solution ("project" in terms of IntelliJ Idea) specific.
We're considering to make `--all-projects` as default parameter but it leads to building issue in some cases. Hope we'll be able to solve it. Stay tuned.
