### ISSUE TITLE
WebStorm Plugin Snyk Vulnerability Scanning depends on unknown plugins

### ISSUE THREAD

**Issue by vyteniskuciauskas-home24** [snyk/snyk-intellij-plugin#2]
`Plugin Snyk Vulnerability Scanning depends on unknown plugins Plugin Snyk Vulnerability Scanning depends on unknown plugins org.jetbrains.plugins.gradle, org.jetbrains.idea.maven, org.jetbrains.idea.maven`

```
WebStorm 2018.3 EAP
Build #WS-183.3283.12, built on October 3, 2018
WebStorm EAP User
Expiration date: November 2, 2018
JRE: 1.8.0_152-release-1343-b3 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-36-generic
```

**Comment by kevinwright** [comment]
WebStorm is not IntelliJ - this is an **IntelliJ** plugin for use with Maven
