### ISSUE TITLE
Open source security error - could not detect target files

### ISSUE THREAD

**Issue by rafek1241** [snyk/snyk-intellij-plugin#245]
![image](https://user-images.githubusercontent.com/9272027/145773352-50286ab9-6eb6-4198-9bc1-f0e1da0ef83a.png)

```
08:55	Snyk
			Could not detect supported target files in C:\Projects\<project-name>.
			Please see our documentation for supported languages and target files: https://snyk.co/udVgQ and make sure you are in the right directory.
```

Project structure:
![image](https://user-images.githubusercontent.com/9272027/145773541-04527282-2edb-42e2-b95d-f077a7d0e8d4.png)

What project?
SLN + few .net projects within src directory and few of them within tests.
SDK: .net core 3.1

**Comment by rafek1241** [comment]
Workaround that worked:
![image](https://user-images.githubusercontent.com/9272027/145774841-7fea4526-0ca7-4f1d-a15d-7d4c4c83cf3c.png)

**Comment by ArtsiomCh** [comment]
@rafek1241 afaik "workaround" above is official way to handle multi-mudules/projects setup. 
Glad You found it and Thanks for reporting!

**Comment by rafek1241** [comment]
@ArtsiomCh 
Okay, should It be treated as `multi-project` if it is single solution?

**Comment by ArtsiomCh** [comment]
Afaik if there're few build files/system under one project/solution/dir then CLI (used under the hood of plugin) will treat it as multi-project one.

**Comment by rafek1241** [comment]
For this plugin parameter '--all-projects' should be set by default. I guess the same thing happen within typical java project, isn't it?
