### ISSUE TITLE
Incompatible with the latest IntelliJ EAP

### ISSUE THREAD

**Issue by abdulisik** [snyk/snyk-intellij-plugin#300]
I'm currently on IntelliJ 2022.1 EAP (it has been about a week since the update) and currently Snyk plugin doesn't work:
_Incompatible: requires IDE build 213.* or earlier_

**Comment by abdulisik** [comment]
Snyk plugin version is 2.4.11 and shows no update available.

**Comment by bastiandoetsch** [comment]
Fixed with [520d3a0](https://github.com/snyk/snyk-intellij-plugin/commit/520d3a0be63824e0d417bb674470529bc865d476)
