### ISSUE TITLE
Enable plugin make auto save as soon as stop typing

### ISSUE THREAD

**Issue by bangbang93** [snyk/snyk-intellij-plugin#324]
https://youtrack.jetbrains.com/issue/WEB-54949

Disable this plugin is resolving the problem.

**Comment by ArtsiomCh** [comment]
Thanks for reporting! We'll investigate.

**Comment by mad4power** [comment]
I have the same issue on Intel Mac but my colleague doesn't have it on Apple Silicon, don't know if that helps

**Comment by ArtsiomCh** [comment]
We're working on that issue. Fix should be available soon (hopefully next week). Stay tuned. Sorry for inconvenience folks...

**Comment by ArtsiomCh** [comment]
Fix released in 2.4.24
Should be available within 2 business days upon JB marketplace approval
