### ISSUE TITLE
Open Source Security - No supported package manager found

### ISSUE THREAD

**Issue by darku77** [snyk/snyk-intellij-plugin#370]
I'm trying to scan some java projects (maven) for vulnerable jars

Some input about the tools being used:
-  Intellij IDEA 2022.1 (Ultimate) - Build #IU-221.5080.210, built on April 12, 2022
-  Snyk 2.4.28
-  maven 3.8.5 - added in Path (Windows)
-  in IDEA this maven is set as well, not the bundled one
-  JAVA_HOME defined (open jdk 17)
- everything is available in Path: java, mvn, snyk - the latter available through node/npm

On the additional parameters I pass "--all-projects" (found here in some closed issues as a suggestion)
I looked as well in some idea logs, did not find anything suspicious 
No other error

scanning a project with snyk from cli works, as well the eclipse plugin

Any idea?

**LE**
After more fiddling around it was helpful to pass the -d parameter in the additional parameters and saw more input, and the problem is somehow that my idea directory is different than the maven modules which I have imported

running snyk cli as will work

snyk test C:\path\to\base_project\ --all-projects

running from the plugin is hangs in "scanning..."

I tried like this: **C:\path\to\base_project\ --all-projects** then like this **test C:\path\to\base_project\ --all-projects**

The version with the --file is not a solution since I guess is not working in the combination of --all-projects

Can you fix something with a base working directory option? or are there any possibilities? My project structure looks like similar to this:

C:\projects\idea_project_base
C:\projects\Lambda\maven_project_a
C:\projects\Lambda\maven_project_a\module_a_1
C:\projects\Lambda\maven_project_a\module_a_2
C:\projects\Lambda\maven_project_b
C:\projects\Lambda\maven_project_b\module_b_1
C:\projects\Lambda\maven_project_b\module_b_2
C:\projects\Lambda\maven_project_c
etc

The scanning will take place in idea_project_base...

**Comment by darku77** [comment]
![image](https://user-images.githubusercontent.com/5212129/165775256-e9f41dfd-cf15-42ea-a2aa-bb213a371372.png)
![image](https://user-images.githubusercontent.com/5212129/165775789-b548b1bd-3f42-4bdf-98e4-9c11009ed115.png)

Repro steps:

- I created an **empty** Idea project: F:\Code\snyk-plugin-test\snyk-plugin-test\idea-base-directory
- I imported in this project a new maven module: F:\Code\snyk-plugin-test\snyk-plugin-test\Base-A which have those 2 children Sub-A-1 and Sub-A-2

Snyk is scanning in the idea-base-directory where the idea metadata is present, as a test I added a pom.xml inside of that folder as well and it works

**Comment by ArtsiomCh** [comment]
Thank you for making such an effort! Could you please upload your example project to GitHub for us to reproduce, please?
On last screenshot I can see that Sub-A-1 and Sub-A-2 are not recognized by Idea as `Source Folders` (i.e. not included into Content Root) and will be definitely not visible to the plugin (and actually to any Idea's action related to the source files).

**Comment by darku77** [comment]
I see some differences in the way you imported and the way I did it

- the **.idea** folder in my case is under the idea base directory, in your case the idea folder is at the top level
- in my case I have 2 top level modules, in your case you have one top level modules
- the pom.xml of Sub-A-3 was just added for testing, in my scenario it was seeing that one and the scanning worked, but not the parent pom of the other top level module **Base-A**

Note: I keep this weird structure because I work for e.g. with 3 projects, they don't have a super maven pom, where all modules would be declared, they are stored in different svn locations etc

So basically
-  I create an empty folder then I create a dumb idea empty project in this location ,here I usually try to keep any idea metadata like the .idea folder, I usually copy runConfigurations etc.. A while ago, there was as well the possibility to keep the .iml files as well at this level, don't know if it's possible now. So at this step I would have **1 top level module**
- Then I go to `File->New->Module from existing sources` and will add each stack manually, in this case, it would be the Base-A. After this I would have **2 top level modules**

Btw if you find this scenario weird, don't invest time in it. 
I created by hand a pom that will declare all this top level projects as modules and will import them at once, as well it's not important anymore to keep the .idea project somewhere elsewhere on disk, it's fine to be at the top level. (does not add any extra benefit, when I had the imls grouped under a folder, yes, in that case it was not keeping any idea meta junk)

 The plugin theoretically works, but I did not manage to scan this pom with bare snyk cli..... 
  and your plugin reports a timeout of 720 seconds, but again this would be a snyk issue, or the fact that I try to analyze like ~80 maven modules with lots and lots of dependencies and there are other smelly parts like the archiva used by maven, is not having a valid certificate and that server might be running a ancient cipher suit for SSL whereas maven 3.8.5/jdk 17 had disabled some ancient stuff by default, so this might be some causes why I'm getting stuck

**Comment by ArtsiomCh** [comment]
Yeah... your setup looks like a very custom one. :)
In the plugin for OSS scan we just run the CLI under the hood in top level project. So, if the bare CLI is not able to find sub-mudules/projects - then plugin will fail to do so too.
afaik (but I'm not an expert here) the CLI just looking for build file in the dir it was invoked and then try to build project based on that. So such top level build file should contain all dependencies in it to be tested properly.
I'll close the issue for now. Feel free to reopen it or create the new one if you need more help!
