### ISSUE TITLE
Not compatible with IDEA 2020.1

### ISSUE THREAD

**Issue by ThexXTURBOXx** [snyk/snyk-intellij-plugin#43]
When starting, it throws the following exception:
https://hastebin.com/ehufujeteh.cs

**Comment by aldanchenko** [comment]
Hello @ThexXTURBOXx 

Thank you for using our product! 

Have you installed the plugin from the IntelliJ repository? The repository now has an outdated version, we have already created an update and soon it will be available via the repository. Could you try the attached plugin zip file, please?

[snyk-intellij-plugin-0.2.2.SNAPSHOT-develop.zip](https://github.com/snyk/snyk-intellij-plugin/files/4523114/snyk-intellij-plugin-0.2.2.SNAPSHOT-develop.zip)

Best regards,
Aleksandr.

**Comment by ThexXTURBOXx** [comment]
Hello @aldanchenko 

Thank you for the fast response!

Yes, i installed it from the repository.
I tried your zip-file, but there is still another issue with that one (it's not the same issue anymore):

Cannot run program "snyk" (in directory "F:/Test"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden

It can't find the snyk executable, even though I installed it via npm.
I can run ```snyk``` from the terminal just fine and the path to snyk is added to the PATH.
What could be the problem this time?

Best regards and thanks a lot,
Nico

**Comment by aldanchenko** [comment]
Hello @ThexXTURBOXx 

Have you installed Snyk CLI as described here - https://support.snyk.io/hc/en-us/articles/360003812458-Getting-started-with-the-CLI?

And could you share your IntelliJ log file, please? This page can help you find it on your OS.

Best regards,
Aleksandr.

**Comment by ThexXTURBOXx** [comment]
Hello @aldanchenko 

Yes, I have installed Snyk CLI as described there (I used the npm method).

The log file is located here: https://pastebin.com/yA8Qgexy

Best regards,
Nico

**Comment by ThexXTURBOXx** [comment]
Hello again,

after trying to install it again via npm, I ended up downloading the precompiled binary from the snyk-GitHub and with that, it finally worked.

Thank you very much and
best regards,
Nico

**Comment by aldanchenko** [comment]
Hello @ThexXTURBOXx 

Happy that everything works!

Best regards,
Aleksandr.
