### ISSUE TITLE
Plugin doesn't seem to be respecting Python virtual env

### ISSUE THREAD

**Issue by arajkumar** [snyk/snyk-intellij-plugin#75]
Plugin lists down the vulnerability for Python only when dependencies are installed globally. Throws error when dependencies are just installed within virtualenv.

Note: Virtual env is properly selected by PyCharm. Refer bottom right side of the screenshot.

<img width="1792" alt="Screenshot 2020-11-26 at 10 24 15 AM" src="https://user-images.githubusercontent.com/3874763/100309713-8a4e7500-2fd1-11eb-889a-d8a65b348cf8.png">

PyCharm version: 2020.2
Snyk Plugin version: 2.0.2

**Comment by aldanchenko** [comment]
Hi @arajkumar,

Thanks for your feedback. We will check it and fix.

Best regards,
Alex

**Comment by aldanchenko** [comment]
Hi @arajkumar 

Please, could you try to setup your virtual environment in Snyk additional properties. For example,

<img width="982" alt="Снимок экрана 2021-01-26 в 18 17 42" src="https://user-images.githubusercontent.com/7049329/105872400-0cbfd900-6003-11eb-8383-d0ba92edd0bb.png">

**Comment by nparry-zymergen** [comment]
Is there any intention of having the plugin use the default Python SDK that is configured for the project? To be clear, I am not sure if that is even possible TBH. But, in a world of python micro services, manually adding the "additional parameters"  command for every micro service seems like an impediment/barrier to entry.

**Comment by bastiandoetsch** [comment]
We would like to be able to do that for the IDEs if possible, but it's not planned as a feature yet. We would need to support the SDK configuration of IntelliJ, PyCharm, GoLand, Webstorm, etc. which can be quite different.

I will close the issue now :).
