### ISSUE TITLE
Failed to test pip project

### ISSUE THREAD

**Issue by flysen** [snyk/snyk-intellij-plugin#84]
- intellij version 2020.2
- snyk plugin version 2.0.4

Added My token to Snyk plugin under general settings.
No custom endpoints.
No additional parameters added.

I have a requirements.txt in the project
`retry==0.9.2
requests==2.24.0`

When running plugin on project:
**Error**
**Path**
  /my/project/path
**Message**
  Failed to test pip project

**Comment by aldanchenko** [comment]
Hi @flysen,

Thanks for your reply and details! I'll test it and let you know.

Best regards,
Alex

**Comment by aldanchenko** [comment]
Hi @flysen 

I can reproduce your issue. For me it happens if requirements in requirements.txt are in one line. For example,

<img width="1397" alt="1" src="https://user-images.githubusercontent.com/7049329/105742599-657c6c80-5f44-11eb-9f7b-17b08f0c61a3.png">

After I split it to different lines it start working.

**Comment by aldanchenko** [comment]
@flysen 

Please, note that the plugin could also show message like this

<img width="1400" alt="2" src="https://user-images.githubusercontent.com/7049329/105742889-b724f700-5f44-11eb-821f-7870ee78ae0a.png">

And you could set different additional properties depending on your local Python installation. For example

<img width="1052" alt="3" src="https://user-images.githubusercontent.com/7049329/105742966-d1f76b80-5f44-11eb-9224-77783ab2c302.png">

**Comment by flysen** [comment]
@aldanchenko Thanks for prompt response :+1: 

Added my virtual env to `Additional parameters` and now it works just fine.

`--command=./venv/bin/python3`

**Comment by aldanchenko** [comment]
Thanks @flysen!

If you don't mind I'll close this issue.
